import { Outfit } from "next/font/google";
import "./globals.css";

// Rename the variable to avoid conflict
const outfitFont = Outfit({
  variable: "--font-outfit", // Changed from --font-geist-mono to be more accurate
  subsets: ["latin"], 
  weight: ["400", "500", "600", "700"]
});

// If you need Geist Mono, you should import and configure it separately
// import { GeistMono } from "next/font/google";
// const geistMono = GeistMono({ subsets: ["latin"] });

export const metadata = {
  title: "Blog App - Awaisi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfitFont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}